# Generated by Django 4.2.11 on 2026-05-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_resume_extracted_text_alter_resume_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='field_scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
